// Single function instead of three for the license link and content. License section is generated by the generateMarkdown function and calls the object using template literal.

function renderLicenseBadge(license) {
switch(license){
  case "MIT":
    return "![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)";
  case "GPL v2":
    return "![License: GPL v2](https://img.shields.io/badge/License-GPL_v2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)";
  case "Apache":
    return "![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)";
  case "None":
    return "Unlicensed";
  }
};


// Function to generate the markdown file. 

function generateMarkdown(data) {

  return `
  
  ${renderLicenseBadge(data.license)}  

  # ${data.title}



  ## Table of Contents  

  * [Installation Instructions](#installation-instructions)  
  * [Usage](#what-is-this-application-used-for)  
  * [License Used](#license-used)  
  * [Contributing Guidelines](#contributing-guidelines)  
  * [Test Instructions](#test-instructions)  
  * [Questions](#questions)  


  ## Installation Instructions   

  ${data.install}


  ## What is this application used for?  

  ${data.usage}  


  ## License Used  

  The license used to cover this application is the ${data.license} license.  


  ## Contributing Guidelines 

  ${data.contributing}  

  ## Test Instructions 


  ${data.tests}  

  ## Questions  

  I can be reached via the following methods:

  * GitHub: [${data.username}](https://github.com/${data.username})  

  * Email Address: ${data.email}    

`;
};

module.exports = generateMarkdown;
